name: Execute queries

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: sudo systemctl start mysql.service
      - uses: actions/checkout@v2
      - run: mysql -uroot -proot -e "SELECT @@version"
      - run: mysql -uroot -proot -e "SHOW DATABASES"
      - run: mysql -uroot -proot < create-databases.sql
      - run: mysql -uroot -proot sandbox < create-tables.sql
      - run: mysql -uroot -proot sandbox -e "SHOW TABLES"
      - run: mysql -uroot -proot sandbox -e "SHOW TRIGGERS\G"
      - run: mysql -uroot -proot sandbox < create-records.sql
      - run: mysql -uroot -proot sandbox -Ns -e "SHOW TABLES" | xargs -I{} mysql -uroot -proot sandbox -e "DESC {}"
      - run: mysql -uroot -proot sandbox -Ns -e "SHOW TABLES" | xargs -I{} mysql -uroot -proot sandbox -e "SHOW INDEX FROM {}"
      - run: mysql -uroot -proot sandbox -Ns -e "SHOW TABLES" | xargs -I{} mysql -uroot -proot sandbox -e "SELECT * FROM {}"
      - run: mysql -uroot -proot sandbox -e "SHOW TABLE STATUS"
      - run: mysql -uroot -proot --verbose sandbox < create-partitions.sql
      - run: mysql -uroot -proot sandbox < show-partitions.sql
      - run: mysql -uroot -proot sandbox < add-partitions.sql
      - run: mysql -uroot -proot sandbox < show-partitions.sql
      - run: mysql -uroot -proot sandbox -e "SHOW CREATE TABLE log_player_names"
      - run: mysql -uroot -proot sandbox -e "SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'sandbox'"
      - run: php generate-dto.php
      - run: mysqldump -uroot -proot --single-transaction sandbox > dump.sql
      - run: cat dump.sql
