name: Execute queries

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: mysql -uroot -proot -e "SHOW DATABASES"
    - run: mysql -uroot -proot < create_database.sql
    - run: mysql -uroot -proot sandbox -e "SHOW TABLES"
