name: Execute queries

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: mysql -uroot -proot -e "SELECT @@version"
      - run: mysql -uroot -proot -e "SHOW DATABASES"
      - run: mysql -uroot -proot < create-databases.sql
      - run: mysql -uroot -proot sandbox < create-tables.sql
      - run: mysql -uroot -proot sandbox -e "SHOW TABLES"
      - run: mysql -uroot -proot sandbox < create-records.sql
      - run: mysql -uroot -proot sandbox -Ns -e "SHOW TABLES" | xargs -I{} mysql -uroot -proot sandbox -e "DESC {}"
      - run: mysql -uroot -proot sandbox -Ns -e "SHOW TABLES" | xargs -I{} mysql -uroot -proot sandbox -e "SHOW INDEX FROM {}"
      - run: mysql -uroot -proot sandbox -Ns -e "SHOW TABLES" | xargs -I{} mysql -uroot -proot sandbox -e "SELECT * FROM {}"
      - run: mysql -uroot -proot sandbox -e "SHOW TABLE STATUS"
      - run: mysql -uroot -proot sandbox < create-partitions.sql
      - run: mysql -uroot -proot sandbox < show-partitions.sql
      - run: mysql -uroot -proot sandbox < add-partitions.sql
      - run: mysql -uroot -proot sandbox < show-partitions.sql
      - run: mysql -uroot -proot sandbox -e "SHOW CREATE TABLE log_player_names"
