name: Execute queries

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: mysql -uroot -proot -e "SHOW DATABASES"
      - run: mysql -uroot -proot < create_databases.sql
      - run: mysql -uroot -proot sandbox < create_tables.sql
      - run: mysql -uroot -proot sandbox -e "SHOW TABLES"
